# Generated by Django 2.1.7 on 2019-03-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_account', '0002_auto_20190327_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cart_number',
            field=models.IntegerField(unique=True),
        ),
    ]
